UPDATE t_p288352_240fps_site_project.components_case SET brand='DEEPCOOL', color='white' WHERE name='DEEPCOOL CC560 WH V2 White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='DEEPCOOL', color='black' WHERE name='DEEPCOOL CG330 3F Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='DEEPCOOL', color='white' WHERE name='DEEPCOOL CG330 4F White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='DEEPCOOL', color='black' WHERE name='DEEPCOOL CH160';
UPDATE t_p288352_240fps_site_project.components_case SET brand='DEEPCOOL', color='black' WHERE name='DEEPCOOL CH690 DIGITAL';
UPDATE t_p288352_240fps_site_project.components_case SET brand='DEEPCOOL', color='black' WHERE name='DEEPCOOL CK560 BLACK';
UPDATE t_p288352_240fps_site_project.components_case SET brand='DEEPCOOL', color='black' WHERE name='DEEPCOOL MATREXX 30';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Formula', color='white' WHERE name='Formula Air Power G5 белый без БП ATX 1x120mm 1xUSB3.0 1xUSB3.1 audio bott PSU';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Formula', color='black' WHERE name='Formula Crystal U1M Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Formula', color='black' WHERE name='Formula Crystal U2M Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Formula', color='black' WHERE name='Formula Crystal U9 Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Formula', color='black' WHERE name='Formula Crystal Z8G Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Formula', color='black' WHERE name='Formula Crystal Z9M Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Formula', color='black' WHERE name='Formula line Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Formula', color='black' WHERE name='Formula V Air Mesh G6 SA Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Jonsbo', color='white' WHERE name='Jonsbo C6 White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Lian-Li', color='black' WHERE name='Lian-Li 011 VISION COMPACT Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Lian-Li', color='white' WHERE name='Lian-Li 011 VISION COMPACT White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Lian-Li', color='white' WHERE name='Lian-Li 011 VISION White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Lian-Li', color='black' WHERE name='Lian-Li Lancool III RGB MidTower';
