UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='black' WHERE name='1STPLAYER Megaview MV5-T Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='white' WHERE name='1STPLAYER Megaview MV5-T White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='black' WHERE name='1STPLAYER Megaview MV6-T Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='white' WHERE name='1STPLAYER Megaview MV6-T White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='black' WHERE name='1STPLAYER Megaview MV8-TP Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='black' WHERE name='1STPLAYER MIKU Mi5 Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='white' WHERE name='1STPLAYER MIKU Mi5 White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='black' WHERE name='1STPLAYER MIKU Mi7-A Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='black' WHERE name='1STPLAYER Steam Punk SP9';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='black' WHERE name='1STPLAYER STEAMPUNK Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='black' WHERE name='1STPLAYER Uview RT5-BK Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='white' WHERE name='1STPLAYER Uview RT5-WH White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='black' WHERE name='1STPLAYER Uview UV5 Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='white' WHERE name='1STPLAYER Uview UV5 White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='black' WHERE name='1STPLAYER Uview UV6 Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='1STPLAYER', color='white' WHERE name='1STPLAYER Uview UV6 White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='ACCORD', color='black' WHERE name='ACCORD ACC-EM01 Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='AeroCool', color='black' WHERE name='AeroCool Cylon Mini RGB Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Ardor Gaming', color='black' WHERE name='Ardor Gaming C305 V2 Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Ardor Gaming', color='black' WHERE name='ARDOR GAMING CGM Minicase Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Ardor Gaming', color='black' WHERE name='Ardor Gaming CK560 Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Ardor Gaming', color='white' WHERE name='Ardor Gaming Crystal cc1 White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Cougar', color='black' WHERE name='Cougar DUOFACE PRO ARGB';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Cougar', color='black' WHERE name='Cougar FV150 RGB Midtower black 4x120mm ARGB';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Cougar', color='white' WHERE name='Cougar FV150 RGB Midtower White 4x120mm ARGB';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Cougar', color='black' WHERE name='Cougar MX110 RGB Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Cougar', color='black' WHERE name='Cougar Puritas RGB Black Fuul-Window';
