UPDATE t_p288352_240fps_site_project.components_case SET brand='Montech', color='black' WHERE name='Montech Air 1000 lite';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Montech', color='black' WHERE name='Montech King 95 Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Montech', color='white' WHERE name='Montech King 95 PRO White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Montech', color='black' WHERE name='Montech Sky TWO Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Montech', color='black' WHERE name='Montech XR ARGB Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Ocypus', color='black' WHERE name='Ocypus GAMMA C52 Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Ocypus', color='white' WHERE name='Ocypus GAMMA C52 White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Ocypus', color='white' WHERE name='Ocypus Lota C70 White ARGB';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Ocypus', color='black' WHERE name='Ocypus Lota C72 Black ARGB';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Ocypus', color='white' WHERE name='Ocypus Lota C72 White ARGB';
UPDATE t_p288352_240fps_site_project.components_case SET brand='PCCooler', color='black' WHERE name='PCCooler C3B310 Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='PCCooler', color='white' WHERE name='PCCooler C3B310 White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Phanteks', color='black' WHERE name='Phanteks Evolv S2 Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='PowerCase', color='black' WHERE name='PowerCase ByteFlow Micro Black LE';
UPDATE t_p288352_240fps_site_project.components_case SET brand='PowerCase', color='white' WHERE name='PowerCase ByteFlow Micro White LE';
UPDATE t_p288352_240fps_site_project.components_case SET brand='PowerCase', color='white' WHERE name='PowerCase Vision Micro M2 White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='PowerCase', color='black' WHERE name='PowerCase Vision Micro M5B Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Xastra', color='white' WHERE name='XASTRA Q500 7ARGB White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Xastra', color='white' WHERE name='XASTRA Q600 White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Xastra', color='white' WHERE name='XASTRA Q700 7ARG White';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Xastra', color='black' WHERE name='XASTRA Q700 7ARGB-C10-UC Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='Xastra', color='black' WHERE name='Xastra QW500M 3ARGB-C10-UC Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='XPG', color='black' WHERE name='XPG STARKER AIR BTF Black';
UPDATE t_p288352_240fps_site_project.components_case SET brand='ZALMAN', color='white' WHERE name='ZALMAN Z9 NEO белый';
